### ISSUE TITLE
Use ansible to create cuckoo user

### ISSUE THREAD

**Issue by kuza55** [SpoonBoy/cuckoo-ansible#6]
I haven't used this myself, but it seems odd that adding a user is a separate step, rather than part of the ansible config.

http://stackoverflow.com/questions/19292899/creating-a-new-user-and-password-with-ansible

**Comment by SpoonBoy** [comment]
I'm using VM to test this playbook,
It's was just easier to me to make the user before running ansible,
the end goal of course is full automation, so i'll have to look at the user module of ansible.
Or maybe @kuza55 if you could give some help on this point, it would be really appreciate :+1:
